# Do NOT Edit This File If You Do NOT Know What You Doing :)

# this is an extension for editing table data
# table data are stored in an numpy ndarray
# the np array can be access by calling tableWidget.model().array
# to modify the data simply do array[row][column] = new_data
# if modify the shape of array, tableWidget.setModel(tableModel(ndarray, headers= headers))
# good luck !

def main(commandBar, printOutLabel, tableWidget, tableModel):
    import numpy as np

    text = commandBar.text()

    def print(text):
        printOutLabel.setText(str(text))
# write your functions here

#    def someFunc():
#        print('done some function')

# End of all functions
    try:
        text = compile(text, 'user', 'exec')
        exec(text)
    except Exception as e:
        print(e)
